# 网站基本信息
title: 我的GitHub博客
description: 基于GitHub Pages的个人博客
author: 您的名字
baseurl: ""
url: "https://你的用户名.github.io"

# 博客设置
permalink: /:year/:month/:day/:title.html
paginate: 10

# 主题设置
theme: light
allow_theme_switch: true

# 语言设置
default_language: "zh"
available_languages:
  - "zh"
  - "en"

# 私密仓库配置（仅供构建脚本参考）
private_repositories_enabled: true 