title: 洋葱王八
description: 洋葱王八的个人博客
baseurl: ""
url: "https://yangcongwangba.github.io"

collections:
  posts:
    output: true
    permalink: /posts/:title
  pages:
    output: true
    permalink: /:title
  projects:
    output: true
    permalink: /projects/:title
  events:    # 示例：新的内容类型
    output: true
    permalink: /events/:title
  news:      # 示例：新的内容类型
    output: true
    permalink: /news/:title

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
