name: 构建和部署

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ oauth_callback ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 处理 OAuth 回调
        if: github.event_name == 'repository_dispatch' && github.event.action == 'oauth_callback'
        env:
          GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
          CODE: ${{ github.event.client_payload.code }}
        run: |
          # 获取访问令牌
          TOKEN_RESPONSE=$(curl -s -X POST \
            -H "Accept: application/json" \
            -d "client_id=${GITHUB_CLIENT_ID}&client_secret=${GITHUB_CLIENT_SECRET}&code=${CODE}" \
            https://github.com/login/oauth/access_token)
          
          # 从响应中提取访问令牌
          ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | grep -o '"access_token":"[^"]*"' | cut -d'"' -f4)
          
          # 如果成功获取令牌，更新管理后台页面
          if [ ! -z "$ACCESS_TOKEN" ]; then
            # 创建临时 HTML 文件，用于将令牌保存到本地存储
            cat > admin/token.html << EOF
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <title>GitHub OAuth 回调</title>
                <script>
                    localStorage.setItem('temp_oauth_token', '${ACCESS_TOKEN}');
                    window.location.href = '/admin/';
                </script>
            </head>
            <body>
                <p>认证成功，正在重定向...</p>
            </body>
            </html>
            EOF
            
            # 提交更改
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add admin/token.html
            git commit -m "添加临时 OAuth 令牌页面"
            git push
          else
            echo "获取访问令牌失败"
            exit 1
          fi

      - name: 构建网站
        if: github.event_name == 'push'
        run: |
          # 在这里可以添加任何必要的构建步骤
          # 例如：jekyll、npm build 等
          echo "构建网站..."
          
          # 如果存在临时令牌页面，删除它
          if [ -f "admin/token.html" ]; then
            rm admin/token.html
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add admin/token.html
            git commit -m "删除临时 OAuth 令牌页面"
            git push
          fi 